#!/bin/sh

if [ $# -lt 3 ]
then
  echo usage: getTableInfo \<sa-login\> \<sa-password\> \<DB name\> [ \<table name\> ]  [ \<Measurement Unit: K/M\> ]
  exit
fi

if [ x$SYBASE = x ]
then
  echo getTableInfo: Please set your SYBASE environment variable to the directory where Sybase SQL Server is installed
  exit
fi


if [ ! -d $SYBASE/bin ]
then
  echo getTableInfo: \$SYBASE/bin directory not found
  exit
fi

saLogin=$1
saPassword=$2

dbName=$3
tableName=$4
sizeUnit=$5

$SYBASE/bin/isql -U$saLogin -P$saPassword << !
USE $dbName
GO
sp_dbinfo $tableName $sizeUnit
GO

!